### ISSUE TITLE
Test de l'association site et chatbox 

### ISSUE THREAD

**Issue by MbiamouRichy** [MbiamouRichy/MR-DIGITAL#12]

**Comment by MbiamouRichy** [comment]
Bon on passe a cette etape

**Comment by MbiamouRichy** [comment]
Mdr mobirise utilise des bibliothèques (Bootstrap) différentes de cette de angular

**Comment by MbiamouRichy** [comment]
Bon je laisse d'abord ca comme ca

**Comment by Rosvelt8** [comment]
Il faut pas laisser je vais trouver un moyen , vu que c'est sur les mêmes bases de language

**Comment by MbiamouRichy** [comment]
tu as trouve le moyen
